Repository kubestellar/kubeflex, pull requests merged in 2025-09, with the labels that each got.

#535 🌱 update dco to skip check for dependabot
  .github/workflows/dco.yaml
Labels: dco-signoff: yes, size/S

#536 📖 docs: remove OCM-type control plane usage examples
  docs/contributors.md
  docs/users.md
Labels: dco-signoff: yes, approved, size/L, needs-ok-to-test

#531 🐛fix(kubeconfig): validate and ignore invalid saved hosting context, warn instead of failing
  cmd/kflex/ctx/ctx.go
  pkg/kubeconfig/extensions.go
  pkg/kubeconfig/extensions_test.go
  pkg/kubeconfig/kubeconfig.go
Labels: dco-signoff: yes, lgtm, size/M, approved

#538 ✨ Brew formula update for kubeflex version v0.9.1
  kflex.rb
Labels: dco-signoff: no, size/S

#542 ✨Change the Helm chart to ensure kubeflex-system ns existence
  Makefile
  chart/templates/install-hooks.yaml
  chart/templates/namespace.yaml
  docs/users.md
Labels: dco-signoff: yes, lgtm, size/M, approved
