Repository kubestellar/kubeflex, pull requests merged in 2025-06, with the labels that each got.

#386 ✨ Usage of Extensions
  cmd/kflex/common/flags.go
  cmd/kflex/create/create.go
  cmd/kflex/ctx/ctx.go
  cmd/kflex/ctx/ctx_test.go
  cmd/kflex/ctx/delete.go
  cmd/kflex/ctx/rename.go
  cmd/kflex/delete/delete.go
  cmd/kflex/init/init.go
  cmd/kflex/main.go
  docs/users.md
  pkg/kubeconfig/extensions.go
  pkg/kubeconfig/extensions_test.go
  pkg/kubeconfig/kubeconfig.go
Labels: dco-signoff: yes, size/XL, lgtm, approved, ok-to-test

#390 ✨ Add `kflex config set-hosting`
  cmd/kflex/config/config.go
  cmd/kflex/config/config_test.go
  cmd/kflex/config/set_hosting_cluster_ctx.go
  cmd/kflex/config/set_hosting_cluster_ctx_test.go
  cmd/kflex/ctx/ctx_test.go
  cmd/kflex/ctx/delete_test.go
  cmd/kflex/ctx/rename_test.go
  cmd/kflex/list/list.go
  cmd/kflex/main.go
  docs/users.md
  pkg/kubeconfig/extensions.go
  pkg/kubeconfig/kubeconfig.go
Labels: dco-signoff: yes, lgtm, approved, size/L, needs-ok-to-test

#399 🐛In Makefile for add ko-local-build as dependency for installing a local chart
  Makefile
Labels: dco-signoff: yes, lgtm, size/XS, approved, needs-ok-to-test

#396 🐛 update helm version from 3.14.0 to 3.16.4
  chart/templates/postgresql.yaml
  config/samples/postcreate-hooks/openshift-crds.yaml
  config/samples/postcreate-hooks/postgres.yaml
Labels: dco-signoff: yes, lgtm, size/XS, approved, needs-ok-to-test

#416 ✨ new(403): add k3s control plane type
  api/v1alpha1/controlplane_types.go
Labels: enhancement, go, LFX Mentorship, dco-signoff: yes, size/M, needs-ok-to-test

#422 ✨ new(418): write k3s apiserver resource def
  pkg/reconcilers/k3s/README.md
  pkg/reconcilers/k3s/apiserver.go
  pkg/reconcilers/k3s/service.go
Labels: LFX Mentorship, dco-signoff: yes, size/M, needs-ok-to-test

#426 ✨ new(423): generate k3s service
  cmd/cmupdate/main.go
  config/manager/config.yaml
  pkg/reconcilers/k3s/service.go
  pkg/reconcilers/k8s/reconciler.go
  pkg/reconcilers/k8s/service.go
  pkg/reconcilers/ocm/reconciler.go
  pkg/reconcilers/ocm/service.go
  pkg/reconcilers/shared/config.go
  pkg/reconcilers/shared/route.go
  pkg/reconcilers/vcluster/service.go
Labels: go, LFX Mentorship, dco-signoff: yes, size/L, needs-ok-to-test

#432 🐛Lxf/431: solve k3s server pod error
  pkg/reconcilers/k3s/apiserver.go
  test/dev/k3stest.yaml
Labels: bug, go, LFX Mentorship, dco-signoff: yes, size/L, needs-ok-to-test

#439 ✨ feature : add control plane name to kubeflex extension data
  pkg/kubeconfig/kubeconfig.go
  pkg/kubeconfig/kubeconfig_test.go
Labels: dco-signoff: yes, lgtm, size/M, approved, needs-ok-to-test

#440 🌱 test : verifies kflex create works as intended after updating AssignControlPlaneToContext
  test/e2e/manage-type-k8s.sh
Labels: enhancement, go, dco-signoff: yes, lgtm, size/S, approved, needs-ok-to-test

#445 📖 answer of why postgresql is a post create hook job
  docs/architecture.md
  docs/postgresql-architecture-decision.md
Labels: dco-signoff: yes, lgtm, approved, size/L, needs-ok-to-test
