Repository kubestellar/kubeflex, pull requests merged in 2025-05, with the labels that each got.

#370 ✨ Bump version of kube-rbac-proxy image from 0.18.0 to 0.19.1
  .github/workflows/test-e2e.yaml
  chart/templates/operator.yaml
  config/default/manager_auth_proxy_patch.yaml
Labels: lgtm

#374 ✨ add OWNERS file
  OWNERS
Labels: dco-signoff: yes, size/XS

#378 🐛 update brew instructions in README.md
  README.md
Labels: dco-signoff: yes, lgtm, size/XS, approved

#377 ✨ Brew formula update for kubeflex version v0.8.9
  kflex.rb
Labels: lgtm, dco-signoff: no, size/S, approved

#373 🐛 add controlplane metadata at creation
  cmd/kflex/common/cp.go
  cmd/kflex/create/create.go
  cmd/kflex/ctx/ctx.go
  cmd/kflex/ctx/get.go
  cmd/kflex/init/init.go
  cmd/kflex/list/list.go
  pkg/kubeconfig/config-util.go
  pkg/kubeconfig/kubeconfig.go
  test/e2e/manage-ctx.sh
Labels: dco-signoff: yes, size/XL, lgtm, approved
